package com.trendmicro.boothapp.ui

import android.Manifest
import android.content.Intent
import android.content.pm.PackageManager
import android.os.Bundle
import android.util.Log
import android.widget.Toast
import androidx.activity.result.contract.ActivityResultContracts
import androidx.appcompat.app.AppCompatActivity
import androidx.camera.core.CameraSelector
import androidx.camera.core.ImageAnalysis
import androidx.camera.core.Preview
import androidx.camera.lifecycle.ProcessCameraProvider
import androidx.core.content.ContextCompat
import com.google.gson.Gson
import com.google.gson.JsonObject
import com.google.mlkit.vision.barcode.BarcodeScanning
import com.google.mlkit.vision.barcode.common.Barcode
import com.google.mlkit.vision.common.InputImage
import com.trendmicro.boothapp.R
import com.trendmicro.boothapp.data.AppPreferences
import com.trendmicro.boothapp.databinding.ActivityQrScanBinding
import java.util.concurrent.Executors

/**
 * Scans a QR code generated by the Chrome extension to auto-fill
 * S3 config and connection settings in the Android app.
 *
 * Expected QR payload:
 * {
 *   "type": "boothapp-pair",
 *   "v": 1,
 *   "s3Bucket": "...",
 *   "s3Region": "...",
 *   "presignEndpoint": "...",
 *   "awsAccessKeyId": "...",
 *   "awsSecretAccessKey": "...",
 *   "awsSessionToken": "..."
 * }
 */
class QrScanActivity : AppCompatActivity() {

    private lateinit var binding: ActivityQrScanBinding
    private lateinit var prefs: AppPreferences
    private var scanned = false

    private val cameraPermissionLauncher = registerForActivityResult(
        ActivityResultContracts.RequestPermission()
    ) { granted ->
        if (granted) {
            startCamera()
        } else {
            Toast.makeText(this, R.string.camera_permission_required, Toast.LENGTH_LONG).show()
            finish()
        }
    }

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        binding = ActivityQrScanBinding.inflate(layoutInflater)
        setContentView(binding.root)

        prefs = AppPreferences(this)

        binding.btnCancel.setOnClickListener { finish() }

        if (ContextCompat.checkSelfPermission(this, Manifest.permission.CAMERA)
            == PackageManager.PERMISSION_GRANTED
        ) {
            startCamera()
        } else {
            cameraPermissionLauncher.launch(Manifest.permission.CAMERA)
        }
    }

    @androidx.camera.core.ExperimentalGetImage
    private fun startCamera() {
        val cameraProviderFuture = ProcessCameraProvider.getInstance(this)
        cameraProviderFuture.addListener({
            val cameraProvider = cameraProviderFuture.get()

            val preview = Preview.Builder().build().also {
                it.surfaceProvider = binding.previewView.surfaceProvider
            }

            val scanner = BarcodeScanning.getClient()
            val analysisExecutor = Executors.newSingleThreadExecutor()

            val imageAnalysis = ImageAnalysis.Builder()
                .setBackpressureStrategy(ImageAnalysis.STRATEGY_KEEP_ONLY_LATEST)
                .build()

            imageAnalysis.setAnalyzer(analysisExecutor) { imageProxy ->
                val mediaImage = imageProxy.image
                if (mediaImage != null && !scanned) {
                    val inputImage = InputImage.fromMediaImage(
                        mediaImage, imageProxy.imageInfo.rotationDegrees
                    )
                    scanner.process(inputImage)
                        .addOnSuccessListener { barcodes ->
                            for (barcode in barcodes) {
                                if (barcode.valueType == Barcode.TYPE_TEXT ||
                                    barcode.valueType == Barcode.TYPE_UNKNOWN
                                ) {
                                    val raw = barcode.rawValue ?: continue
                                    if (handleQrPayload(raw)) {
                                        scanned = true
                                        return@addOnSuccessListener
                                    }
                                }
                            }
                        }
                        .addOnCompleteListener {
                            imageProxy.close()
                        }
                } else {
                    imageProxy.close()
                }
            }

            cameraProvider.unbindAll()
            cameraProvider.bindToLifecycle(
                this, CameraSelector.DEFAULT_BACK_CAMERA, preview, imageAnalysis
            )
        }, ContextCompat.getMainExecutor(this))
    }

    private fun handleQrPayload(raw: String): Boolean {
        try {
            val gson = Gson()
            val json = gson.fromJson(raw, JsonObject::class.java)

            if (json.get("type")?.asString != "boothapp-pair") return false

            val bucket = json.get("s3Bucket")?.asString ?: ""
            val region = json.get("s3Region")?.asString ?: ""
            val presign = json.get("presignEndpoint")?.asString ?: ""
            val accessKey = json.get("awsAccessKeyId")?.asString ?: ""
            val secretKey = json.get("awsSecretAccessKey")?.asString ?: ""

            // Save to preferences
            prefs.awsAccessKeyId = accessKey
            prefs.awsSecretAccessKey = secretKey
            // presignEndpoint acts as the orchestrator URL for the app
            if (presign.isNotBlank()) {
                prefs.orchestratorUrl = presign
            }

            Log.d(TAG, "QR pairing successful: bucket=$bucket region=$region")

            runOnUiThread {
                Toast.makeText(this, "Paired successfully!", Toast.LENGTH_SHORT).show()
                val resultIntent = Intent()
                resultIntent.putExtra(EXTRA_PAIRED, true)
                resultIntent.putExtra(EXTRA_BUCKET, bucket)
                resultIntent.putExtra(EXTRA_REGION, region)
                setResult(RESULT_OK, resultIntent)
                finish()
            }

            return true
        } catch (e: Exception) {
            Log.w(TAG, "QR parse failed: ${e.message}")
            return false
        }
    }

    companion object {
        private const val TAG = "QrScanActivity"
        const val EXTRA_PAIRED = "paired"
        const val EXTRA_BUCKET = "bucket"
        const val EXTRA_REGION = "region"
    }
}
