#!/usr/bin/env bash
# deploy-presenter.sh — Deploy the BoothApp presenter dashboard
#
# Installs dependencies, configures environment, starts with PM2,
# sets up systemd for auto-restart, and optionally configures nginx.
#
# Usage:
#   bash scripts/deploy-presenter.sh [--port 3000] [--domain boothapp.trendcyberrange.com]
#
set -euo pipefail

# ── Defaults ───────────────────────────────────────────────────────────────────

PORT=3000
DOMAIN=""
S3_BUCKET="boothapp-sessions-752266476357"
AWS_REGION="us-east-1"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
PRESENTER_DIR="$REPO_ROOT/presenter"
APP_NAME="boothapp-presenter"

# ── Parse args ─────────────────────────────────────────────────────────────────

while [[ $# -gt 0 ]]; do
  case "$1" in
    --port)
      PORT="$2"
      shift 2
      ;;
    --domain)
      DOMAIN="$2"
      shift 2
      ;;
    --s3-bucket)
      S3_BUCKET="$2"
      shift 2
      ;;
    --region)
      AWS_REGION="$2"
      shift 2
      ;;
    -h|--help)
      echo "Usage: bash scripts/deploy-presenter.sh [OPTIONS]"
      echo ""
      echo "Options:"
      echo "  --port PORT       Server port (default: 3000)"
      echo "  --domain DOMAIN   Domain for nginx (optional)"
      echo "  --s3-bucket NAME  S3 bucket name"
      echo "  --region REGION   AWS region (default: us-east-1)"
      echo "  -h, --help        Show this help"
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      exit 1
      ;;
  esac
done

# ── Helpers ────────────────────────────────────────────────────────────────────

info()  { echo "[deploy] $*"; }
ok()    { echo "[  ok  ] $*"; }
fail()  { echo "[ FAIL ] $*" >&2; }

# ── Preflight checks ──────────────────────────────────────────────────────────

info "Checking prerequisites..."

if ! command -v node &>/dev/null; then
  fail "node not found. Install Node.js >= 18 first."
  exit 1
fi

NODE_MAJOR=$(node -e "console.log(process.versions.node.split('.')[0])")
if [[ "$NODE_MAJOR" -lt 18 ]]; then
  fail "Node.js $NODE_MAJOR found, >= 18 required."
  exit 1
fi
ok "Node.js v$(node --version | tr -d v)"

if ! command -v npm &>/dev/null; then
  fail "npm not found."
  exit 1
fi
ok "npm $(npm --version)"

if [ ! -d "$PRESENTER_DIR" ]; then
  fail "Presenter directory not found: $PRESENTER_DIR"
  exit 1
fi
ok "Presenter directory exists"

# ── Step 1: Install dependencies ───────────────────────────────────────────────

info "Installing Node.js dependencies..."
cd "$PRESENTER_DIR"
npm install --production
ok "npm install complete"

# ── Step 2: Configure environment ──────────────────────────────────────────────

info "Writing .env..."
cat > "$PRESENTER_DIR/.env" <<ENVEOF
# BoothApp Presenter Environment — generated by deploy-presenter.sh
S3_BUCKET=$S3_BUCKET
AWS_REGION=$AWS_REGION
PORT=$PORT
ENVEOF
ok ".env written (PORT=$PORT, S3_BUCKET=$S3_BUCKET, AWS_REGION=$AWS_REGION)"

# ── Step 3: Install and start with PM2 ────────────────────────────────────────

info "Setting up PM2..."

if ! command -v pm2 &>/dev/null; then
  info "PM2 not found globally, installing..."
  npm install -g pm2
fi
ok "PM2 $(pm2 --version)"

# Stop existing instance if running
pm2 delete "$APP_NAME" 2>/dev/null || true

pm2 start "$PRESENTER_DIR/server.js" \
  --name "$APP_NAME" \
  --cwd "$PRESENTER_DIR" \
  --env production \
  -- --port "$PORT"

pm2 save
ok "PM2 process '$APP_NAME' started on port $PORT"

# ── Step 4: Systemd service for auto-restart on reboot ─────────────────────────

info "Configuring systemd for PM2 startup..."

if command -v systemctl &>/dev/null; then
  # pm2 startup generates a systemd unit that restores saved processes on boot
  PM2_STARTUP_CMD=$(pm2 startup systemd -u "$(whoami)" --hp "$HOME" 2>&1 | grep "sudo" | head -1 || true)

  if [[ -n "$PM2_STARTUP_CMD" ]]; then
    info "Running PM2 startup command..."
    eval "$PM2_STARTUP_CMD" 2>/dev/null || {
      # If we're already root or it's already configured, this is fine
      info "PM2 startup may already be configured (non-fatal)"
    }
  fi

  # Also create a dedicated systemd unit as a fallback
  SERVICE_FILE="/etc/systemd/system/${APP_NAME}.service"
  if [ -w /etc/systemd/system/ ] || [ "$(id -u)" -eq 0 ]; then
    cat > "$SERVICE_FILE" <<SVCEOF
[Unit]
Description=BoothApp Presenter Dashboard
After=network.target

[Service]
Type=simple
User=$(whoami)
WorkingDirectory=$PRESENTER_DIR
ExecStart=$(command -v node) $PRESENTER_DIR/server.js
Restart=on-failure
RestartSec=5
Environment=PORT=$PORT
Environment=S3_BUCKET=$S3_BUCKET
Environment=AWS_REGION=$AWS_REGION
EnvironmentFile=-$PRESENTER_DIR/.env

[Install]
WantedBy=multi-user.target
SVCEOF

    systemctl daemon-reload
    systemctl enable "$APP_NAME" 2>/dev/null || true
    ok "Systemd service created and enabled: $SERVICE_FILE"
  else
    info "No write access to /etc/systemd/system/ — skipping dedicated service unit"
    info "PM2 startup handles auto-restart instead"
  fi
else
  info "systemctl not available — PM2 startup handles auto-restart"
fi

# ── Step 5: Nginx reverse proxy (if installed) ────────────────────────────────

if command -v nginx &>/dev/null; then
  info "Nginx detected, configuring reverse proxy..."

  SERVER_NAME="${DOMAIN:-_}"
  NGINX_CONF="/etc/nginx/sites-available/${APP_NAME}"
  NGINX_ENABLED="/etc/nginx/sites-enabled/${APP_NAME}"

  if [ -w /etc/nginx/ ] || [ "$(id -u)" -eq 0 ]; then
    # Ensure sites-available and sites-enabled directories exist
    mkdir -p /etc/nginx/sites-available /etc/nginx/sites-enabled

    cat > "$NGINX_CONF" <<NGXEOF
server {
    listen 80;
    server_name ${SERVER_NAME};

    location / {
        proxy_pass http://127.0.0.1:${PORT};
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_cache_bypass \$http_upgrade;
    }
}
NGXEOF

    # Enable site
    ln -sf "$NGINX_CONF" "$NGINX_ENABLED"

    # Remove default site if it conflicts on port 80
    if [ -f /etc/nginx/sites-enabled/default ]; then
      rm -f /etc/nginx/sites-enabled/default
      info "Removed default nginx site to avoid port 80 conflict"
    fi

    # Test and reload
    if nginx -t 2>/dev/null; then
      systemctl reload nginx 2>/dev/null || nginx -s reload 2>/dev/null || true
      ok "Nginx reverse proxy configured: $SERVER_NAME -> 127.0.0.1:$PORT"
    else
      fail "Nginx config test failed — check $NGINX_CONF"
    fi
  else
    info "No write access to /etc/nginx/ — skipping nginx configuration"
    info "Manually proxy port 80 -> $PORT if needed"
  fi
else
  info "Nginx not installed — server available directly on port $PORT"
fi

# ── Verify ─────────────────────────────────────────────────────────────────────

info "Verifying deployment..."
sleep 2

VERIFY_PASS=0
VERIFY_FAIL=0

verify() {
  local label="$1"
  local url="$2"
  local expect="$3"

  RESPONSE=$(curl -sf "$url" 2>/dev/null || echo "")
  if echo "$RESPONSE" | grep -q "$expect"; then
    ok "$label"
    VERIFY_PASS=$((VERIFY_PASS + 1))
  else
    fail "$label"
    VERIFY_FAIL=$((VERIFY_FAIL + 1))
  fi
}

verify "GET / (index.html)"        "http://127.0.0.1:${PORT}/"           "<html"
verify "GET /sessions.html"        "http://127.0.0.1:${PORT}/sessions.html" "<html"
verify "GET /timeline.html"        "http://127.0.0.1:${PORT}/timeline.html" "<html"
verify "GET /api/health"           "http://127.0.0.1:${PORT}/api/health"    '"status":"ok"'
verify "GET /api/config"           "http://127.0.0.1:${PORT}/api/config"    '"s3_bucket"'
verify "GET /api/pages"            "http://127.0.0.1:${PORT}/api/pages"     '"pages"'

echo ""
echo "====================================="
echo "  Deployment complete"
echo "  Server: http://127.0.0.1:${PORT}"
if [[ -n "$DOMAIN" ]]; then
  echo "  Domain: http://${DOMAIN}"
fi
echo "  Checks: ${VERIFY_PASS} passed, ${VERIFY_FAIL} failed"
echo "====================================="

if [[ "$VERIFY_FAIL" -gt 0 ]]; then
  echo ""
  echo "Some checks failed. Run 'pm2 logs $APP_NAME' to debug."
  exit 1
fi
